### PR TITLE
rename npm project to uport-credentials

### PR DESCRIPTION
**Pull request by pelle**

### CODE REVIEW

**Comment by localredhead** [comment]
LGMT

**Comment by Eseoghene** [comment]
We need to ensure that we use npm-deprecate to publish this change so old users are not left in the lurch

**Comment by Eseoghene** [comment]
We will also need to inform developers to require uport-credentials in the codebase

**Comment by pelle** [comment]
@Eseoghene yes we'll communicate it as part of our overall communication of the major releases

**Pull request merged**
